// This file is regenerated by Desktop Studio : modify it carefully !

popup = POPUPS.hledatProdukt = POPUPS.popup({ hledatProdukt: {
	template: e.popup.template.NoButton,
	url: "hledatProdukt\\popup.html",
	CX: 500,
	CY: 300,
	X: e.popup.position.Center,
	Y: e.popup.position.Center
}});

GLOBAL.events.START.on(function (ev) {
	if (ctx.options.isDebug) {
		systray.addMenu("", "TestPopup", "Test popups");
		systray.addMenu("TestPopup", "hledatProduktOpen" , "Open hledatProdukt", "", function(ev) {
			POPUPS.hledatProdukt.open({ testMode: true });
		});
		systray.addMenu("TestPopup", "hledatProduktClose" , "Close hledatProdukt", "", function(ev) {
			POPUPS.hledatProdukt.close();
		});
	}
});

POPUPS.hledatProdukt.onTest(function(popup) {	
	// TODO : add your tests here
});

popup.item({ text1: {
	type: e.item.type.text,
	icon: e.item.icon.user,
	iconStyle: e.item.style.None,
	iconSide: e.item.side.left,
	label: "Name: ",
	test: "klávesnice",
	inputStyle: e.item.inputStyle.None,
	placeholder: "Type test here",
	parent: "",
	auto: true,
	feedbackIcon: e.item.icon.none,
	size: e.item.size.Medium
}});

popup.item({ button1: {
	type: e.item.type.button,
	parent: "",
	value: "Hledat",
	tooltip: "",
	style: e.item.style.Blue,
	icon: e.item.icon.none,
	iconSide: e.item.side.left,
	badge: "",
	badgeStyle: e.item.style.None,
	size: e.item.size.Medium,
	close: false,
	submit: false,
	disabled: false,
	right: false,
	justified: false,
	fa: "",
	animated: false,
	pulse: false,
	auto: true,
	tooltipPlacement: e.item.side.none,
	iconStyle: e.item.style.None
}});

