srvbuild.release_directory: /opt/sap_ase
srvbuild.product: sqlsrv
srvbuild.server_name: SapFed_ds
srvbuild.sa_password: sybase
srvbuild.new_config: yes
srvbuild.do_add_server: yes
srvbuild.do_upgrade: no
srvbuild.network_protocol_list: tcp
srvbuild.network_hostname_list: FedKbw
srvbuild.network_port_list: 2025
srvbuild.application_type: MIXED
srvbuild.server_page_size: 4k
srvbuild.master_device_physical_name: /opt/sap_ase/data/master.dat
srvbuild.master_device_size: 52
srvbuild.master_database_size: 26
srvbuild.errorlog: /opt/sap_ase/ASE-16_0/install/SAPFed_ds.log
srvbuild.sybsystemprocs_device_physical_name: /opt/sap_ase/data/sysprocs.dat
srvbuild.sybsystemprocs_device_size: 196
srvbuild.sybsystemprocs_database_size: 196
srvbuild.sybsystemdb_device_physical_name: /opt/sap_ase/data/sybsysdb.dat
srvbuild.sybsystemdb_device_size: 6
srvbuild.sybsystemdb_database_size: 6
srvbuild.tempdb_device_physical_name: /opt/sap_ase/data/tempdbdev.dat
srvbuild.tempdb_device_size: 100
srvbuild.tempdb_database_size: 100
srvbuild.default_backup_server: SapFed_bs
srvbuild.addl_cmdline_parameters: 
srvbuild.shmem: /opt/sap_ase/ASE-16_0
srvbuild.do_configure_pci: no
srvbuild.sybpcidb_device_physical_name: /opt/sap_ase/data/sybpcidbdev_data.dat
srvbuild.sybpcidb_device_size: 48
srvbuild.sybpcidb_database_size: 48
srvbuild.do_optimize_config: yes
srvbuild.avail_physical_memory: 2000
srvbuild.avail_cpu_num: 1
srvbuild.configure_remote_command_and_control_agent_ase: USE_DEFAULT
srvbuild.enable_ase_for_ase_cockpit_monitor: no
srvbuild.technical_user: tech_user
srvbuild.technical_user_password: sybase
srvbuild.addl_build_parameters: 
